#!/bin/sh
sudo /sbin/ifconfig eth1 ${1} netmask ${2} up
sudo /sbin/route add default gw ${3} eth1
# drop the defalt gataway of eth0
sudo /sbin/route del default dev eth0 2>/dev/null || true

sudo cat <<EOF | sudo tee /etc/network/interfaces > /dev/null
# Generated by nise-bosh-vagrant

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto eth0
iface eth0 inet dhcp
    post-up /bin/sleep 5; /sbin/route del default dev \$IFACE

#VAGRANT-BEGIN
auto eth1
iface eth1 inet static
    address ${1}
    netmask ${2}
    gateway ${3}
#VAGRANT-END
EOF
